name: Deploy OnyxMicr Static Site

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: webapp

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
